# Generated by Django 3.1.5 on 2021-01-07 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0003_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='blog',
        ),
    ]
